### ISSUE TITLE
Latest version doesn't compile with Java 11.0.7

### ISSUE THREAD

**Issue by Geminii** [stripe/stripe-java#1079]
Hi everybody :) 

I want to implement Billing portal session into my project. 
I update it to latest version but it seems to have some problem during compilation : 

```
constituent[0]: file:/usr/local/Cellar/maven/3.6.2/libexec/conf/logging/
constituent[1]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-compat-3.6.2.jar
constituent[2]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-resolver-util-1.4.1.jar
constituent[3]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-plugin-api-3.6.2.jar
constituent[4]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-settings-builder-3.6.2.jar
constituent[5]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/plexus-cipher-1.7.jar
constituent[6]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/plexus-interpolation-1.25.jar
constituent[7]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-resolver-spi-1.4.1.jar
constituent[8]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/guice-4.2.1-no_aop.jar
constituent[9]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/slf4j-api-1.7.25.jar
constituent[10]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/plexus-component-annotations-2.0.0.jar
constituent[11]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/cdi-api-1.0.jar
constituent[12]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-resolver-provider-3.6.2.jar
constituent[13]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-artifact-3.6.2.jar
constituent[14]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/jcl-over-slf4j-1.7.25.jar
constituent[15]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-slf4j-provider-3.6.2.jar
constituent[16]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/plexus-utils-3.2.1.jar
constituent[17]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/plexus-sec-dispatcher-1.4.jar
constituent[18]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/commons-cli-1.4.jar
constituent[19]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-resolver-transport-wagon-1.4.1.jar
constituent[20]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-repository-metadata-3.6.2.jar
constituent[21]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-model-builder-3.6.2.jar
constituent[22]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/commons-io-2.5.jar
constituent[23]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/jansi-1.17.1.jar
constituent[24]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-embedder-3.6.2.jar
constituent[25]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-resolver-connector-basic-1.4.1.jar
constituent[26]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-resolver-api-1.4.1.jar
constituent[27]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-model-3.6.2.jar
constituent[28]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-settings-3.6.2.jar
constituent[29]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/org.eclipse.sisu.inject-0.3.3.jar
constituent[30]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/wagon-file-3.3.3.jar
constituent[31]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/wagon-http-3.3.3-shaded.jar
constituent[32]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-shared-utils-3.2.1.jar
constituent[33]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-builder-support-3.6.2.jar
constituent[34]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-core-3.6.2.jar
constituent[35]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/maven-resolver-impl-1.4.1.jar
constituent[36]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/org.eclipse.sisu.plexus-0.3.3.jar
constituent[37]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/javax.inject-1.jar
constituent[38]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/wagon-provider-api-3.3.3.jar
constituent[39]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/commons-lang3-3.8.1.jar
constituent[40]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/guava-25.1-android.jar
constituent[41]: file:/usr/local/Cellar/maven/3.6.2/libexec/lib/jsr250-api-1.0.jar
---------------------------------------------------
Exception in thread "main" java.lang.AssertionError
	at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:155)
	at jdk.compiler/com.sun.tools.javac.util.Assert.check(Assert.java:46)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.enter(Modules.java:247)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.readSourceFile(JavaCompiler.java:837)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ImplicitCompleter.complete(JavacProcessingEnvironment.java:1529)
	at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:642)
	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1326)
	at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.complete(Type.java:1140)
	at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.getTypeArguments(Type.java:1066)
	at jdk.compiler/com.sun.tools.javac.code.Printer.visitClassType(Printer.java:237)
	at jdk.compiler/com.sun.tools.javac.code.Printer.visitClassType(Printer.java:52)
	at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.accept(Type.java:993)
	at jdk.compiler/com.sun.tools.javac.code.Printer.visit(Printer.java:136)
	at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArgument(AbstractDiagnosticFormatter.java:199)
	at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArguments(AbstractDiagnosticFormatter.java:167)
	at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:111)
	at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:67)
	at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArgument(AbstractDiagnosticFormatter.java:185)
	at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArguments(AbstractDiagnosticFormatter.java:167)
	at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:111)
	at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:67)
	at jdk.compiler/com.sun.tools.javac.util.JCDiagnostic.getMessage(JCDiagnostic.java:788)
	at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$DiagnosticSourceUnwrapper.getMessage(ClientCodeWrapper.java:799)
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:131)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:952)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:158)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

I'm working with version : 
``` 
➜  java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
➜  mvn -v
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)
Maven home: /usr/local/Cellar/maven/3.6.2/libexec
Java version: 11.0.7, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: fr_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.5", arch: "x86_64", family: "mac"
```

Did i miss something ? 
It seems to work until version 15.0.0 but not after.

Thanks a lot for your great help :) 
Have a nice day too.

**Comment by remi-stripe** [comment]
@Geminii Thanks for reaching out and sorry to hear about the troubles here. Unfortunately the crash you shared is quite cryptic and it would be hard to pinpoint what could be causing this without more details. Can you confirm that you can compile a really simple and basic example that only uses stripe-java and nothing else in your application?

**Comment by richardm-stripe** [comment]
Hi @Geminii, I'm closing due to inactivity, but feel free to reopen if you can provide more details and determine this is related  to `stripe-java`.
