### ISSUE TITLE
Webhook.constructEvent() issue 

### ISSUE THREAD

**Issue by lilachf1** [stripe/stripe-java#1122]
Hi,

I'm upgrading to the new Stripe issuing version '2020-08-27' from '2018-11-08'.
In my code i get the webhook event by: Webhook.constructEvent(payload, signature, secret))
and audit that event (com.stripe.model.Event.class) to mongo.
I found out that the new event looks different in the mongoDB in the manner of:
instead of getting a 'key:value' structure i get a 
'key:  {
           value: , 
           class: 
}'  
(where the class is for example JsonPrimitive)
that causes an exception to be thrown when trying to fetch a record from the mongoDB (please stacktrace see attached).
*please notice: It worked just fine with the '2018-11-08' version.
Could you please advise?

The exception i get :
`org.springframework.data.mapping.model.MappingInstantiationException: Failed to instantiate com.google.gson.JsonPrimitive using constructor NO_CONSTRUCTOR with arguments 

	at org.springframework.data.convert.ReflectionEntityInstantiator.createInstance(ReflectionEntityInstantiator.java:67)
	at org.springframework.data.convert.ClassGeneratingEntityInstantiator.createInstance(ClassGeneratingEntityInstantiator.java:84)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:321)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:294)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readMap(MappingMongoConverter.java:1168)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:265)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readValue(MappingMongoConverter.java:1554)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1452)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readProperties(MappingMongoConverter.java:427)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.populateProperties(MappingMongoConverter.java:344)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:324)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:294)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readValue(MappingMongoConverter.java:1554)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1452)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readProperties(MappingMongoConverter.java:427)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.populateProperties(MappingMongoConverter.java:344)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:324)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:294)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readValue(MappingMongoConverter.java:1554)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1452)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readProperties(MappingMongoConverter.java:427)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.populateProperties(MappingMongoConverter.java:344)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:324)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:294)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.readValue(MappingMongoConverter.java:1554)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$MongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1452)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$AssociationAwareMongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1501)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$AssociationAwareMongoDbPropertyValueProvider.getPropertyValue(MappingMongoConverter.java:1464)
	at org.springframework.data.mapping.model.PersistentEntityParameterValueProvider.getParameterValue(PersistentEntityParameterValueProvider.java:71)
	at org.springframework.data.mapping.model.SpELExpressionParameterValueProvider.getParameterValue(SpELExpressionParameterValueProvider.java:49)
	at org.springframework.data.convert.ClassGeneratingEntityInstantiator$EntityInstantiatorAdapter.extractInvocationArguments(ClassGeneratingEntityInstantiator.java:250)
	at org.springframework.data.convert.ClassGeneratingEntityInstantiator$EntityInstantiatorAdapter.createInstance(ClassGeneratingEntityInstantiator.java:223)
	at org.springframework.data.convert.ClassGeneratingEntityInstantiator.createInstance(ClassGeneratingEntityInstantiator.java:84)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:321)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:294)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:225)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:221)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.read(MappingMongoConverter.java:94)
	at org.springframework.data.mongodb.core.MongoTemplate$ReadDocumentCallback.doWith(MongoTemplate.java:3162)
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindOneInternal(MongoTemplate.java:2757)
	at org.springframework.data.mongodb.core.MongoTemplate.doFindOne(MongoTemplate.java:2481)
	at org.springframework.data.mongodb.core.MongoTemplate.findOne(MongoTemplate.java:820)
	at org.springframework.data.mongodb.core.MongoTemplate.findOne(MongoTemplate.java:807)
`

**Comment by richardm-stripe** [comment]
Hello @lilachf1. I'm not certain but you may be encountering the "event deserialization" breaking change that we introduced some time ago. See the [migration guide](https://github.com/stripe/stripe-java/wiki/Migration-guide-for-v9#event-deserialization).
There is also some a [javadoc](https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/EventDataObjectDeserializer.java#L11-L49) with some additional information about how event deserialization works, particularly with regard to API version mismatches.

I'm optimistically closing this issue, but feel free to reopen if this is not the problem you are encountering. In that case,
could you provide a code example that demonstrates the unexpected behavior from `stripe-java` in isolation, without involving MongoDB?

**Comment by lilachf1** [comment]
Hello @richardm-stripe Richard, 

After some more investigation i found the issue.
It is related to the event deserialization but in a different way.
I already knew about the new way of extracting the StipeObject and implemented it that way. 
However, i'm auditing the whole Event and not just the Stripe Object, therefore the only line relevant from the code below is the first one where i use the webhook.constructEvent which is a Stripe method i get from the sdk, nothing to implement from my side here. 

**Event event = Webhook.constructEvent(payload, sigHeader, secret);**
EventDataObjectDeserializer dataObjectDeserializer = event.getDataObjectDeserializer();
if (dataObjectDeserializer.getObject().isPresent()) {
StripeObject stripeObject = dataObjectDeserializer.getObject().get();
     ... 
} else {...}


What happens is related to the way spring data mongo works and your EventData.object  type change:
When saving a record to mongo, Spring Data MongoDB adds '_class' in the mongo documents to handle polymorphic behavior of java inheritance. 
when saving the object to the database it is simply serialized into JSON string, 
but when deserializing it back to POJO, to avoid polymorphism ambiguities it uses the stored _class.
When you changed the EventData.object type from StripeObject to JsonObject, it began to store not just one _class  for the whole StripeObject but _class for each entity of it.
And when inflating the pojo by reflection the mongo requires not just the _class, but also constructors.
It fails when trying to inflate the first entity of the new object, the "id" field, it looks for a no-args constructor for this JsonPrimitive class but there's no such, and we get no default constructor found and the nested exception is noSuchMethodException <init>().

FYI
