### ISSUE TITLE
Problem with your last version for addDiscount

### ISSUE THREAD

**Issue by Kenji94** [stripe/stripe-java#1131]
Hi,

I just tried your last version: 
com.stripe:stripe-java:20.19.0
Add `discounts` to SessionCreateParams
https://github.com/stripe/stripe-java/pull/1130/files

Here is my code:
```
SessionCreateParams.Discount discount = SessionCreateParams.Discount.builder()
          .setCoupon(couponWrapper.getCouponType().getId())
          .putAllExtraParam(new HashMap<>()) // I tried without this line too
          .setPromotionCode(couponWrapper.getStripePromoCodeId())
          .build();
builder.addDiscount(discount);
```
Here is the error I got:
```
com.stripe.exception.InvalidRequestException: Received unknown parameter: discounts; code: parameter_unknown; request-id: req_FRywWJwSktbPOH
	at com.stripe.net.LiveStripeResponseGetter.handleApiError(LiveStripeResponseGetter.java:157)
	at com.stripe.net.LiveStripeResponseGetter.request(LiveStripeResponseGetter.java:61)
	at com.stripe.net.ApiResource.request(ApiResource.java:179)
	at com.stripe.net.ApiResource.request(ApiResource.java:169)
	at com.stripe.model.checkout.Session.create(Session.java:359)
	at com.stripe.model.checkout.Session.create(Session.java:352)
	at guemard.neovel.feature.payment.init.InitiatePaymentManager.createSession(InitiatePaymentManager.java:320)
```

Do you have any idea how to fix this ?
Thanks a lot in advance,
Thibault

**Comment by remi-stripe** [comment]
@Kenji94 Thanks for reaching out and sorry for the confusion. The parameter is brand new and hasn't been made public in the API just yet. We shipped it in client libraries in advance of the release next week so that anyone can use it immediately once it's public.

The parameter should become available next Monday and then you can use it as expected.
