### ISSUE TITLE
Integrating with Quarkus

### ISSUE THREAD

**Issue by rjsoph** [stripe/stripe-java#1199]
Has anyone successfully integrated a Webhook processor on Quarkus?

I am having trouble deserializing the Event object.....

Resource class looks like this.....

    @Path("/stripe-events/{realm}")
    @POST
    public Response stripeEvents(@PathParam("realm") String realm, @HeaderParam("Stripe-Signature") String sig, @RequestBody String event) {
            stripe.processEvent(realm,sig,event);
            return Response.ok().build();
    }

Service layout looks like this and the exception is thrown in the Webhook.constructEvent()

    @Transactional
    public void
    processEvent(String realm, String sig, String payload) {
        StripeAccount account = stripeRepo.getAccount(realm); // retrieves the secret from db
        if (account == null) {
            throw new ApiException(realm + " not found", 404);
        }

        Event event = null;
        try {
            event = Webhook.constructEvent(payload, sig, account.getSecret());
        } catch (SignatureVerificationException e) {
            log.error("invalid event signature");
            throw new ApiException("invalid request",400);
        } catch (JsonSyntaxException e) {
            log.error("invalid event object");
            throw new ApiException("invalid request",400);
        }

The event object looks like this.....

{
  "created": 1326853478,
  "livemode": false,
  "id": "evt_00000000000000",
  "type": "plan.created",
  "object": "event",
  "request": null,
  "pending_webhooks": 1,
  "api_version": "2020-08-27",
  "data": {
    "object": {
      "id": "price_00000000000000",
      "object": "plan",
      "active": true,
      "aggregate_usage": null,
      "amount": 2000,
      "amount_decimal": "2000",
      "billing_scheme": "per_unit",
      "created": 1618961865,
      "currency": "usd",
      "interval": "month",
      "interval_count": 1,
      "livemode": false,
      "metadata": {
      },
      "nickname": null,
      "product": "prod_00000000000000",
      "tiers_mode": null,
      "transform_usage": null,
      "trial_period_days": null,
      "usage_type": "licensed"
    }
  }
}

The stack trace is here.....

23:08:19 ERROR [io.qu.ve.ht.ru.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /pay/stripe-events/micro failed, error id: 7278eee5-4677-4505-abc6-8586db3b018f-3: org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Unable to invoke no-args constructor for class com.stripe.model.Event. Registering an InstanceCreator with Gson for this type may fix this problem.
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.lang.RuntimeException: Unable to invoke no-args constructor for class com.stripe.model.Event. Registering an InstanceCreator with Gson for this type may fix this problem.
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:228)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at com.stripe.net.Webhook.constructEvent(Webhook.java:49)
	at com.stripe.net.Webhook.constructEvent(Webhook.java:30)
	at com.sophware.pay.StripeService.processEvent(StripeService.java:38)
	at com.sophware.pay.StripeService_Subclass.processEvent$$superaccessor1(StripeService_Subclass.zig:235)
	at com.sophware.pay.StripeService_Subclass$$function$$1.apply(StripeService_Subclass$$function$$1.zig:47)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:127)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:100)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:340)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.sophware.pay.StripeService_Subclass.processEvent(StripeService_Subclass.zig:188)
	at com.sophware.pay.StripeService_ClientProxy.processEvent(StripeService_ClientProxy.zig:163)
	at com.sophware.pay.PayResource.stripeEvents(PayResource.java:23)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 17 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Method.java:566)
	at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:50)
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:225)
	... 52 more
Caused by: java.lang.IllegalArgumentException: Class com.stripe.model.Event is instantiated reflectively but was never registered. Register the class by using org.graalvm.nativeimage.hosted.RuntimeReflection
	at com.oracle.svm.core.graal.snippets.SubstrateAllocationSnippets.hubErrorStub(SubstrateAllocationSnippets.java:247)
	at sun.misc.Unsafe.allocateInstance(Unsafe.java:840)
	... 55 more

**Comment by remi-stripe** [comment]
@rjsoph In the majority of cases like this the problem is that your framework/system is not giving you the raw payload. It's giving you a modified version of the string, for example changing the indentation or format, and because of this the signature does not match.

I'd recommend contacting our support team for help as this is not a bug with the stripe-java library: https://support.stripe.com/contact

**Comment by rjsoph** [comment]
Has anyone gotten the Webhook.constructEvent() to work as a Quarkus native application?

The exact code works in dev mode as well as in a JVM container but when compiled as a native executable it throws this exception.

Russ.

**Comment by romixch** [comment]
I try to accomplish the same thing as you @rjsoph. I think what is missing is some information for graalVMs Ahead-Of-Time compiler to correctly compile the Stripe library to native code. One way could be to include a file `native-image.properties` in the library. With that everyone could simply include stripe-java in any graalVM native-image project.

This could result in a pull-request to stripe. The question is if stripe would be willing to acept such a pull request? @remi-stripe

**Comment by romixch** [comment]
GraalVM describes how this works in it's documentation: https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/

**Comment by richardm-stripe** [comment]
Hello @romixch and @rjsoph,

We'd consider a contribution along these lines, but it would need to be well-explained, ideally with an example we could run, and we'd also have to consider the maintenance it would represent. Definitely interested in becoming compatible with more runtimes, especially if it's a simple change.

I've never used Quarkus myself, but I did some quick googling -- could the fix for this be related to "registering classes for reflection" ([Docs](https://quarkus.io/guides/writing-native-applications-tips#using-the-registerforreflection-annotation))?

>The elements used via reflection are not part of the call tree so they are dead code eliminated (if not called directly in other cases). To include these elements in your native executable, you need to register them for reflection explicitly.
> This is a very common case as JSON libraries typically use reflection to serialize the objects to JSON:

That smells like what's going on here because the stack trace involves GSON, and the exception is mentioning a missing constructor which might be caused by this dead code elimination.

**Comment by romixch** [comment]
Yes, I think that is exactly what is missing here. But I think it would be better to solve it generally for GraalVM native images and not just for Quarkus. There are many other platforms that would benefit from that. Even Spring Boot has an initiative to support GraalVM native images: https://spring.io/blog/2021/03/11/announcing-spring-native-beta
Maybe we can generate the configuration at stripe-java build time so that GraalVM can pick this up when generating the native image. That saves you from thinking at GraalVM every time you change or add some model class.

**Comment by romixch** [comment]
I have now a configuration that works with Quarkus and GraalVM. I could publish this as GitHub project or as a separate jar on maven central. @rjsoph : Would you be interested in it?

**Comment by romixch** [comment]
You may want to have a look at https://github.com/romixch/stripe-java-graalvm

**Comment by krisgerhard** [comment]
I'm using this simple extension for native image. https://github.com/krisgerhard/quarkiverse-stripe
Adds all com.stripe.model classes for reflection. Unpolished solution but I made it public if anyone else is interested.
