### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration in Android  7

### ISSUE THREAD

**Issue by HexScience** [stripe/stripe-java#1253]
I am using JAVA SDK for retrieve subscription. app is crashing due to class not fount in android 7.

E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.mybeat, PID: 4603
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:325)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;
        at com.stripe.net.HttpClient.<clinit>(HttpClient.java:17)
        at com.stripe.net.LiveStripeResponseGetter.buildDefaultHttpClient(LiveStripeResponseGetter.java:111)
        at com.stripe.net.LiveStripeResponseGetter.<init>(LiveStripeResponseGetter.java:42)
        at com.stripe.net.LiveStripeResponseGetter.<init>(LiveStripeResponseGetter.java:33)
        at com.stripe.net.ApiResource.<clinit>(ApiResource.java:35)
        at com.stripe.model.Subscription.retrieve(Subscription.java:550)
        at com.mybeat.activitys.BaseActivity$checkSubscription.doInBackground(BaseActivity.java:181)
        at com.mybeat.activitys.BaseActivity$checkSubscription.doInBackground(BaseActivity.java:145)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.Duration" on path: DexPathList[[zip file "/data/app/com.mybeat-1/base.apk"],nativeLibraryDirectories=[/data/app/com.mybeat-1/lib/x86_64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by remi-stripe** [comment]
@HexScience stripe-java is a library that should be used server-side and never client-side in a mobile application. Retrieving a subscription requires a Secret API key. If you put that key in your mobile application, an attacker can find it and then do whatever they want on your account including refunding all charges for example. There's an official [Android SDK](https://github.com/stripe/stripe-android) that you should use instead but this is limited to client-side operations such as collecting card details or confirming a PaymentIntent.
