### ISSUE TITLE
Exception thrown when converting Json to Gson `com.google.gson.JsonSyntaxException`

### ISSUE THREAD

**Issue by abdullahsaf** [stripe/stripe-java#1267]
Please only file issues here that you believe represent actual bugs or feature requests for the Stripe Java library.
An exception is thrown when returning a successful request of endpoint confirm `paymentIntent` due to failed conversion of Json to Gson with following stacktrace:

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 24 column 33 path $.charges.data[0].balance_transaction
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at com.company.stripe.StripeAPI.confirmPaymentIntent(StripeAPI.java:138)
	at com.company.stripe.StripeAPI.main(StripeAPI.java:198)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 24 column 33 path $.charges.data[0].balance_transaction
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 15 more

```
The Json response for the request is:
```
{
  "id": "pi_id",
  "object": "payment_intent",
  "amount": 100000,
  "amount_capturable": 0,
  "amount_received": 100000,
  "application": null,
  "application_fee_amount": null,
  "canceled_at": null,
  "cancellation_reason": null,
  "capture_method": "automatic",
  "charges": {
    "object": "list",
    "data": [
      {
        "id": "ch_id",
        "object": "charge",
        "amount": 100000,
        "amount_captured": 100000,
        "amount_refunded": 0,
        "application": null,
        "application_fee": null,
        "application_fee_amount": null,
        "balance_transaction": "txn_id",
        "billing_details": {
          "address": {
            "city": null,
            "country": null,
            "line1": null,
            "line2": null,
            "postal_code": null,
            "state": null
          },
          "email": null,
          "name": null,
          "phone": null
        },
        "calculated_statement_descriptor": "Company LTD",
        "captured": true,
        "created": 1633190016,
        "currency": "usd",
        "customer": null,
        "description": null,
        "destination": null,
        "dispute": null,
        "disputed": false,
        "failure_code": null,
        "failure_message": null,
        "fraud_details": {
        },
        "invoice": null,
        "livemode": false,
        "metadata": {
        },
        "on_behalf_of": null,
        "order": null,
        "outcome": {
          "network_status": "approved_by_network",
          "reason": null,
          "risk_level": "normal",
          "risk_score": 4,
          "seller_message": "Payment complete.",
          "type": "authorized"
        },
        "paid": true,
        "payment_intent": "pi_id",
        "payment_method": "pm_id",
        "payment_method_details": {
          "card": {
            "brand": "visa",
            "checks": {
              "address_line1_check": null,
              "address_postal_code_check": null,
              "cvc_check": null
            },
            "country": "US",
            "exp_month": 10,
            "exp_year": 2022,
            "fingerprint": "fingerprint_hash",
            "funding": "credit",
            "installments": null,
            "last4": "4242",
            "network": "visa",
            "three_d_secure": null,
            "wallet": null
          },
          "type": "card"
        },
        "receipt_email": null,
        "receipt_number": null,
        "receipt_url": "https://pay.stripe.com/receipts/acct_id/ch_id/rcpt_id",
        "refunded": false,
        "refunds": {
          "object": "list",
          "data": [

          ],
          "has_more": false,
          "total_count": 0,
          "url": "/v1/charges/ch_id/refunds"
        },
        "review": null,
        "shipping": null,
        "source": null,
        "source_transfer": null,
        "statement_descriptor": null,
        "statement_descriptor_suffix": null,
        "status": "succeeded",
        "transfer_data": null,
        "transfer_group": null
      }
    ],
    "has_more": false,
    "total_count": 1,
    "url": "/v1/charges?payment_intent=pi_id"
  },
  "client_secret": "pi_id_secret_id",
  "confirmation_method": "automatic",
  "created": 1633189980,
  "currency": "usd",
  "customer": null,
  "description": null,
  "invoice": null,
  "last_payment_error": null,
  "livemode": false,
  "metadata": {
  },
  "next_action": null,
  "on_behalf_of": null,
  "payment_method": "pm_id",
  "payment_method_options": {
    "card": {
      "installments": null,
      "network": null,
      "request_three_d_secure": "automatic"
    }
  },
  "payment_method_types": [
    "card"
  ],
  "receipt_email": null,
  "review": null,
  "setup_future_usage": null,
  "shipping": null,
  "source": null,
  "statement_descriptor": null,
  "statement_descriptor_suffix": null,
  "status": "succeeded",
  "transfer_data": null,
  "transfer_group": null
}

```
and the request payload only included id for `payent_method`. The exception is only thrown if the `paymentIntent` is confirmed, no problem is faced for other responses.

I am using Java 1.8 and the latest Stripe Library.

Thanks.

**Comment by dcr-stripe** [comment]
Hi @abdullahsaf, sorry to hear you're having issues!

Would you be able to provide a sample of how you are making this call?  This works out of the box for me, but the stack trace you linked seems be erroring outside the stripe-java package : `com.company.stripe.StripeAPI.confirmPaymentIntent(StripeAPI.java:138)`. 

Given that there's a `Gson.fromJson` call there which causes the issue, I'd like to understand what `GSON` instance is being used and whether this is responsible.

Thanks!

**Comment by abdullahsaf** [comment]
Hey @dcr-stripe 
> Given that there's a `Gson.fromJson` call there which causes the issue, I'd like to understand what `GSON` instance is being used and whether this is responsible. 
Yes, I there is `Gson.fromJson` in my call. I also tried `GsonBuilder().create().fromJson` but same issue. The call to stripe was successful and I attached the response above. Let me know if you need to know anything else. 
Thanks.

**Comment by dcr-stripe** [comment]
Hi @abdullahsaf 

Could you post your code showing you set up your GSON instance and make the call? Are you using the [`ApiResource.GSON` public instance](https://github.com/stripe/stripe-java/blob/d727355237e6766b593ecd38d5e7967060f395c4/src/main/java/com/stripe/net/ApiResource.java#L39)?

Thanks!

**Comment by abdullahsaf** [comment]
> Hi @abdullahsaf
> 
> Could you post your code showing you set up your GSON instance and make the call? Are you using the [`ApiResource.GSON` public instance](https://github.com/stripe/stripe-java/blob/d727355237e6766b593ecd38d5e7967060f395c4/src/main/java/com/stripe/net/ApiResource.java#L39)?
> 
> Thanks!

```java
	public PaymentIntent confirmPaymentIntent(String intentId, String paymentMethodId) {
		Response response = null;
		try {
			response = stripeEndpoints.confirmPaymentIntent(authorization, intentId, paymentMethodId);
			String request = response.readEntity(String.class);
			System.out.println("request- confirm " + request);
			PaymentIntent intentObj = new GsonBuilder().create().fromJson(request, PaymentIntent.class);
			System.out.println(intentObj);
			return intentObj;
		} finally {
			response.close();
		}
	}
```
This is my code for the method

**Comment by dcr-stripe** [comment]
> > Hi @abdullahsaf
> > Could you post your code showing you set up your GSON instance and make the call? Are you using the [`ApiResource.GSON` public instance](https://github.com/stripe/stripe-java/blob/d727355237e6766b593ecd38d5e7967060f395c4/src/main/java/com/stripe/net/ApiResource.java#L39)?
> > Thanks!
> 
> ```java
> 	public PaymentIntent confirmPaymentIntent(String intentId, String paymentMethodId) {
> 		Response response = null;
> 		try {
> 			response = stripeEndpoints.confirmPaymentIntent(authorization, intentId, paymentMethodId);
> 			String request = response.readEntity(String.class);
> 			System.out.println("request- confirm " + request);
> 			PaymentIntent intentObj = new GsonBuilder().create().fromJson(request, PaymentIntent.class);
> 			System.out.println(intentObj);
> 			return intentObj;
> 		} finally {
> 			response.close();
> 		}
> 	}
> ```
> 
> This is my code for the method

Thank you for posting this!

The issue here is you are creating a new `GSON` instance from scratch using `new GsonBuilder().create()`. This instance isn't configured with our `TypeAdapter`s. If you replace `new GsonBuilder().create()` with `ApiResource.GSON`, this should resolve the issue. You need to use our pre-configured instance for deserialization.

You can see this instance and how it is created at https://github.com/stripe/stripe-java/blob/d727355237e6766b593ecd38d5e7967060f395c4/src/main/java/com/stripe/net/ApiResource.java#L39.

**Comment by abdullahsaf** [comment]
Thanks alot dear @dcr-stripe. Worked!!!!
