### ISSUE TITLE
Creating a Person with API Key specified in the Request Options throws AuthenticationException

### ISSUE THREAD

**Issue by ssozonoff** [stripe/stripe-java#1280]
Hi,

If I take your documented example to create a Person (https://stripe.com/docs/api/persons/create?lang=java) and modify it to provide the API Key as a request option the code throws an exception complaining the API Key is missing.

```
Account account =
  Account.retrieve("acct_1H30E7C6UFOBDM7x");

Map<String, Object> params = new HashMap<>();
params.put("first_name", "Jane");
params.put("last_name", "Diaz");

RequestOptions options = RequestOptions.builder()
                        .setApiKey(stripeKey.get())
                        .build();

Person person = account.persons().create(params, options);
```

This looks like a bug to me, I am using the latest SDK version 20.86.1

```
2021-11-06 18:13:45.656 ERROR 98335 --- [nPool-worker-19] c.l.yyy.xxx.service.StripeService        : No API key provided. Set your API key using `Stripe.apiKey = "<API-KEY>"`. You can generate API keys from the Stripe Dashboard. See https://stripe.com/docs/api/authentication for details or contact support at https://support.stripe.com/email if you have any questions.

com.stripe.exception.AuthenticationException: No API key provided. Set your API key using `Stripe.apiKey = "<API-KEY>"`. You can generate API keys from the Stripe Dashboard. See https://stripe.com/docs/api/authentication for details or contact support at https://support.stripe.com/email if you have any questions.
	at com.stripe.net.StripeRequest.buildHeaders(StripeRequest.java:160) ~[stripe-java-20.86.1.jar:20.86.1]
	at com.stripe.net.StripeRequest.<init>(StripeRequest.java:75) ~[stripe-java-20.86.1.jar:20.86.1]
	at com.stripe.net.LiveStripeResponseGetter.request(LiveStripeResponseGetter.java:57) ~[stripe-java-20.86.1.jar:20.86.1]
	at com.stripe.net.ApiResource.request(ApiResource.java:181) ~[stripe-java-20.86.1.jar:20.86.1]
	at com.stripe.net.ApiResource.requestCollection(ApiResource.java:217) ~[stripe-java-20.86.1.jar:20.86.1]
	at com.stripe.model.Account.persons(Account.java:504) ~[stripe-java-20.86.1.jar:20.86.1]
	at com.stripe.model.Account.persons(Account.java:482) ~[stripe-java-20.86.1.jar:20.86.1]
```

Kind thanks,
Serge

**Comment by remi-stripe** [comment]
@ssozonoff the library works as expected here and it's a bug with your code instead. You are trying to pass the API key specifically per API request instead of setting it globally. In your code you are making 3 API requests total but only pass the API key in one of them, the last one, which is what it fails.

First you are retrieving the Account via its id, which is an API request. Then you are listing Persons on that Account, which is another API request. Those 2 calls never get the API key so they don't work. Finally you are creating a new Person in the collection and for that one you pass the API key properly.

Here's a modified version of your code, using proper typed parameters which are easier and cleaner to work with:

```
    RequestOptions requestOptions =
      RequestOptions.builder()
        .setApiKey("sk_test_123")
        .build();

    Account account = Account.retrieve("acct_123, options);

    AccountPersonsParams paramsPersonsList =
      AccountPersonsParams.builder()
        .build();

    PersonCollection persons = account.persons(paramsPersonsList, options);

    PersonCollectionCreateParams paramsPersonCreate =
      PersonCollectionCreateParams.builder()
        .setFirstName("Jane")
        .setLastName("Diaz")
        .build();

    Person person = persons.create(paramsPersonCreate, options);

    System.out.println("person - " + person.getId());
```

I'm going to close this out as the library doesn't have a bug here but you can get further help from our support team: https://support.stripe.com/contact
