### ISSUE TITLE
Need help : IOexception during api request to stripe

### ISSUE THREAD

**Issue by CG-neverdie** [stripe/stripe-java#1293]
I'm having internet connection problems.
I use the server provided by the cloud provider to build the website, the website is running on ubuntu20.04 java1.8 nginx
com.stripe.exception.ApiConnectionException: IOException during API request to Stripe (https://api.stripe.com): api.stripe.com Please check your internet connection and try again. If this problem persists,you should check Stripe's service status at https://twitter.com/stripestatus, or let us know at support@stripe.com.
    at com.stripe.net.HttpURLConnectionClient.request(HttpURLConnectionClient.java:54)
    at com.stripe.net.HttpClient.requestWithTelemetry(HttpClient.java:56)
    at com.stripe.net.HttpClient.requestWithRetries(HttpClient.java:82)
    at com.stripe.net.LiveStripeResponseGetter.request(LiveStripeResponseGetter.java:54)
    at com.stripe.net.ApiResource.request(ApiResource.java:179)
    at com.stripe.model.checkout.Session.create(Session.java:345)
    at com.stripe.model.checkout.Session.create(Session.java:338)
    at com.labs.controller.ProductController.pay(ProductController.java:1091)
    at com.labs.controller.ProductController$$FastClassBySpringCGLIB$$88cf7734.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)

**Comment by remi-stripe** [comment]
@CG-neverdie This sounds like a network issue overall. This is something you usually would debug directly with your host provider. You can also use https://github.com/stripe/stripe-reachability/ to try and debug potential issues with them

I'd recommend following up with our support team otherwise if you need more help as it won't be a big with the library itself: https://support.stripe.com/contact
