### ISSUE TITLE
NullPointer for autoPagingIterable

### ISSUE THREAD

**Issue by perotom** [stripe/stripe-java#1305]
I am using `Scala 2.12.8` with lib version `20.97.0`. As the API doesn't provide a counting function, I tried implementing my own. Sadly I always get a`NullPointerException`.

```
val url = String.format("%s%s", Stripe.getApiBase, "/v1/search")
val params: Map[String, Object] = Map(
  "count" -> Integer.valueOf(100),
  "query" -> "is:subscription"
)
val collection = ApiResource.request(ApiResource.RequestMethod.GET, url, params.asJava, classOf[SubscriptionCollection], RequestOptions.getDefault)
val count = collection.autoPagingIterable().asScala.count(_ => true)
```
Output
```
java.lang.NullPointerException
	at com.stripe.model.PagingIterator.hasNext(PagingIterator.java:33)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at com.test.StripeService.$anonfun$countSubscriptions$1(StripeService.scala:95)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

Am I using the `autoPagingIterable()` wrong?

**Comment by dcr-stripe** [comment]
Hi @perotom - thanks for the report!

The `/v1/search` endpoint you're using is meant for the Stripe dashboard and the SDKs aren't generally built to consume these results. Your code is trying to take the result and transform it into a `SubscriptionCollection` which is an SDK concept and therefore failing (admittedly in a non-obvious way). 

The [Search API](https://stripe.com/docs/search-api) is currently under beta if you are interested in a more supported searching experience!

Thanks!
