### ISSUE TITLE
Exception thrown when handling API response errors

### ISSUE THREAD

**Issue by rishikeshjoshi** [stripe/stripe-java#1415]
### Describe the bug

An exception is thrown when handling API errors. E.g. trying to retrieve a non-existent session. On running the below snippet it throws the below exception

```
java.lang.IllegalArgumentException: Refusing to create type reflection-based type adapter for external class: com.google.gson.JsonObject
	at com.stripe.net.ReflectionCheckingTypeAdapterFactory.create(ReflectionCheckingTypeAdapterFactory.java:20)
	at com.google.gson.Gson.getAdapter(Gson.java:353)
	at com.google.gson.Gson.fromJson(Gson.java:794)
	at com.google.gson.Gson.fromJson(Gson.java:761)
	at com.google.gson.Gson.fromJson(Gson.java:710)
	at com.google.gson.Gson.fromJson(Gson.java:682)
	at com.stripe.net.LiveStripeResponseGetter.handleApiError(LiveStripeResponseGetter.java:169)
	at com.stripe.net.LiveStripeResponseGetter.request(LiveStripeResponseGetter.java:65)
	at com.stripe.net.ApiResource.request(ApiResource.java:181)
	at com.stripe.model.checkout.Session.retrieve(Session.java:430)
	at com.stripe.model.checkout.Session.retrieve(Session.java:414)
```

### To Reproduce

1. Run the below snippet with an apiKey.
2. Notice the exception thrown.

### Expected behavior

A `StripeException` should be thrown instead.

### Code snippets

```Java
Stripe.apiKey = "<apiKey>";
Session session = null;
try { 
  session = Session.retrieve("invalidKey");
}
catch (StripeException e) {
  e.printStackTrace();
}
```

### OS

Ubuntu

### Java version

8

### stripe-java version

21.0.0

### API version

2022-08-01

**Comment by pakrym-stripe** [comment]
Hm, I can't reproduce the issue.

Can you, please, share the output for the following snippet:

```java

import com.stripe.Stripe;
import com.stripe.exception.StripeException;
import com.stripe.model.checkout.Session;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import com.google.gson.internal.GsonBuildConfig;


public class App {
    public static void main(String[] args) throws IOException, StripeException {
        
        System.out.println(System.getProperty("java.version"));
        System.out.println(Session.class.getPackage().getImplementationVersion());
        System.out.println(GsonBuildConfig.VERSION);
    }
}
```

**Comment by rishikeshjoshi** [comment]
I didn't have `GsonBuildConfig` on my classpath, but the Gson version I was using is 2.2.2. After upgrading to the latest version, I can't see the exception anymore. Thanks for your help! 

Output:
```
1.8.0_342
21.0.0
```
