### ISSUE TITLE
IllegalStateException on Event "previous_attributes" field

### ISSUE THREAD

**Issue by leothekim** [stripe/stripe-java#183]
The webhook json generated from the dashboard for the `customer.source.updated` event looks like this:

```
{
  "created": 1326853478,
  "livemode": false,
  "id": "evt_00000000000000",
  "type": "customer.source.updated",
  "object": "event",
  "request": null,
  "pending_webhooks": 1,
  "api_version": "2015-04-07",
  "data": {
    "object": {
      "id": "card_00000000000000",
      "object": "card",
      "last4": "4242",
      "brand": "Visa",
      "funding": "credit",
      "exp_month": 7,
      "exp_year": 2016,
      "country": "US",
      "name": null,
      "address_line1": null,
      "address_line2": null,
      "address_city": null,
      "address_state": null,
      "address_zip": null,
      "address_country": null,
      "cvc_check": "pass",
      "address_line1_check": null,
      "address_zip_check": null,
      "dynamic_last4": null,
      "metadata": {},
      "customer": "cus_00000000000000"
    },
    "previous_attributes": null
  }
}
```

Note the `previous_attributes` field is `null`, which appears to be true for v2015-04-07 and v2015-06-15. When trying to deserialize into an `Event` using `Event.GSON.fromJson(json, Event.class)`, I get this error:

```
java.lang.IllegalStateException: Not a JSON Object: null
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
        at com.google.gson.Gson.fromJson(Gson.java:803)
        at com.google.gson.Gson.fromJson(Gson.java:768)
        at com.google.gson.Gson.fromJson(Gson.java:717)
        at com.google.gson.Gson.fromJson(Gson.java:689)
```

Setting `previous_attributes` to `{}` instead of `null` fixes the problem. Seems like this should be handled in the client library? Am using 1.31.0.

**Comment by leothekim** [comment]
Is `previous_attributes` not supposed to be `null`? If so, why does the test webhook send `null`?

**Comment by leothekim** [comment]
Otherwise, this is a pretty simple fix:
https://gist.github.com/leothekim/0e52f0a7e71ba9150e3d

**Comment by leothekim** [comment]
Thanks!
