### ISSUE TITLE
Error when deserializing a Charge object

### ISSUE THREAD

**Issue by frankie-simon** [stripe/stripe-java#422]
I'm using stripe-java 5.23.0, with Java 1.8.

I have a webhook setup up for the "charge.succeeded" event. The method looks like this.

     @CrossOrigin
     @RequestMapping(path = "/update", method = {RequestMethod.POST}, consumes = MimeTypeUtils.APPLICATION_JSON_VALUE, produces = MimeTypeUtils.APPLICATION_JSON_VALUE)
     public ResponseEntity<MyResponse> update(@RequestBody(required = false) String json) {
        ResponseEntity<MyResponse> re;
       
        Event stripeEvent = Event.GSON.fromJson(json, Event.class);
        logger.info("Endpoint reached with json:{}", json);
        String eventObjJson = stripeEvent.getData().getObject().toJson();
        logger.info("event -> getData -> getObject -> toJson:{}", eventObjJson);

        Charge charge =  Event.GSON.fromJson(stripeEvent.getData().getObject().toJson(), Charge.class);
     }

When testing a successful charge the call fails on the last line, when deserializing the charge object.

Here's the log output of the first log line (the entire event json):
       
    {
        "created": 1326853478,
        "livemode": false,
        "id": "evt_00000000000000",
        "type": "charge.succeeded",
        "object": "event",
        "request": null,
        "pending_webhooks": 1,
        "api_version": "2017-08-15",
        "data": {
        "object": {
            "id": "ch_00000000000000",
            "object": "charge",
            "amount": 4900,
            "amount_refunded": 0,
            "application": null,
            "application_fee": null,
            "balance_transaction": "txn_00000000000000",
            "captured": true,
            "created": 1510158112,
            "currency": "usd",
            "customer": "cus_00000000000000",
            "description": "Description",
            "destination": null,
            "dispute": null,
            "failure_code": null,
            "failure_message": null,
            "fraud_details": {
            },
            "invoice": null,
            "livemode": false,
            "metadata": {
                "responseId": "R_2EtnlHOgqTgV2Zt"
            },
            "on_behalf_of": null,
            "order": null,
            "outcome": {
                "network_status": "approved_by_network",
                "reason": null,
                "risk_level": "normal",
                "seller_message": "Payment complete.",
                "type": "authorized"
            },
            "paid": true,
            "receipt_email": "fdjnfnf@gggg.com",
            "receipt_number": null,
            "refunded": false,
            "refunds": {
                "object": "list",
                "data": [
    
                ],
                "has_more": false,
                "total_count": 0,
                "url": "/v1/charges/ch_1BLwJILN9LSzPoXKTdMF6RiR/refunds"
            },
            "review": null,
            "shipping": null,
            "source": {
                "id": "card_00000000000000",
                "object": "card",
                "address_city": "fhjdfhj",
                "address_country": "United States",
                "address_line1": "fdhdfjhFH",
                "address_line1_check": "pass",
                "address_line2": null,
                "address_state": "NY",
                "address_zip": "12345",
                "address_zip_check": "pass",
                "brand": "Visa",
                "country": "US",
                "customer": "cus_00000000000000",
                "cvc_check": "pass",
                "dynamic_last4": null,
                "exp_month": 11,
                "exp_year": 2029,
                "fingerprint": "wqEb6wBZozp3h9Lp",
                "funding": "credit",
                "last4": "4242",
                "metadata": {
                },
                "name": "name",
                "tokenization_method": null
            },
            "source_transfer": null,
            "statement_descriptor": null,
            "status": "succeeded",
            "transfer_group": null
        }
    }
    }

The exception I get from the last line:
java.lang.NullPointerException: null
	at com.stripe.model.BalanceTransactionDeserializer.deserialize(BalanceTransactionDeserializer.java:57) ~[stripe-java-5.23.0.jar!/:?]
	at com.stripe.model.BalanceTransactionDeserializer.deserialize(BalanceTransactionDeserializer.java:17) ~[stripe-java-5.23.0.jar!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.1.jar!/:?]
	at com.stripe.model.ExpandableFieldDeserializer.deserialize(ExpandableFieldDeserializer.java:36) ~[stripe-java-5.23.0.jar!/:?]
	at com.stripe.model.ExpandableFieldDeserializer.deserialize(ExpandableFieldDeserializer.java:8) ~[stripe-java-5.23.0.jar!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[gson-2.8.1.jar!/:?]
	at com.tapd.um.rest.controller.Stripe.updateToInReview(Stripe.java:54) [classes!/:?]
	at sun.reflect.GeneratedMethodAccessor143.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar!/:3.1.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar!/:3.1.0]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:326) [undertow-core-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812) [undertow-core-1.4.18.Final.jar!/:1.4.18.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

Since I had almost no need for anything besides the meta data - I ended up writing my own minimalistic class just for the id and meta data - but it seems like there's something wrong with the deserialization here.

EDIT: code formatting

**Comment by ob-stripe** [comment]
Hi @frankie-simon. You don't need to reserialize + deserialize the nested charge object. You can simply retrieve it like this:

```java
Event stripeEvent = Event.GSON.fromJson(json, Event.class);
Charge charge = (Charge) stripeEvent.getData().getObject();
```

That said, there is still an issue with our JSON serializer. It seems that `toJson()` does not properly handle expandable attributes. This is the output of `stripeEvent.getData().getObject().toJson()`:

```
{
  "id": "ch_00000000000000",
  "object": "charge",
  "amount": 4900,
  "amount_refunded": 0,
  "application": null,
  "application_fee": null,
  "alternate_statement_descriptors": null,
  "balance_transaction": {
    "id": "txn_00000000000000",
    "expanded_object": null
  },
  "captured": true,
  "created": 1510158112,
  "currency": "usd",
  "customer": {
    "id": "cus_00000000000000",
    "expanded_object": null
  },
  "description": "Description",
  "destination": null,
  "dispute": null,
  "failure_code": null,
  "failure_message": null,
  "fraud_details": {
    "user_report": null,
    "stripe_report": null
  },
  "invoice": null,
  "livemode": false,
  "metadata": {
    "responseId": "R_2EtnlHOgqTgV2Zt"
  },
  "outcome": {
    "network_status": "approved_by_network",
    "reason": null,
    "risk_level": "normal",
    "rule": null,
    "seller_message": "Payment complete.",
    "type": "authorized"
  },
  "order": null,
  "paid": true,
  "receipt_email": "fdjnfnf@gggg.com",
  "receipt_number": null,
  "refunded": false,
  "refunds": {
    "data": [],
    "total_count": 0,
    "has_more": false,
    "request_options": null,
    "request_params": null,
    "url": "/v1/charges/ch_1BLwJILN9LSzPoXKTdMF6RiR/refunds",
    "count": null
  },
  "review": null,
  "shipping": null,
  "source": {
    "address_city": "fhjdfhj",
    "address_country": "United States",
    "address_line1": "fdhdfjhFH",
    "address_line1_check": "pass",
    "address_line2": null,
    "address_state": "NY",
    "address_zip": "12345",
    "address_zip_check": "pass",
    "available_payout_methods": null,
    "brand": "Visa",
    "country": "US",
    "currency": null,
    "cvc_check": "pass",
    "default_for_currency": null,
    "dynamic_last4": null,
    "exp_month": 11,
    "exp_year": 2029,
    "fingerprint": "wqEb6wBZozp3h9Lp",
    "funding": "credit",
    "last4": "4242",
    "name": "name",
    "recipient": null,
    "status": null,
    "three_d_secure": null,
    "tokenization_method": null,
    "description": null,
    "iin": null,
    "issuer": null,
    "type": null,
    "id": "card_00000000000000",
    "object": "card",
    "account": null,
    "customer": "cus_00000000000000",
    "metadata": {}
  },
  "source_transfer": null,
  "statement_descriptor": null,
  "status": "succeeded",
  "transfer": null,
  "transfer_group": null,
  "card": null,
  "disputed": null,
  "statement_description": null
}
```

We will look into this and push a fix. Thanks for the report!
