### ISSUE TITLE
java.lang.NoSuchFieldError: isEC Inside Charge.Create(chargeMap)

### ISSUE THREAD

**Issue by colangelo-david** [stripe/stripe-java#495]
Im working on a new stripe integration on a java project and have hit what im pretty sure is a bug. Essentially when I call Charge.Create(chargeMap) I get the following exception, stack dump as follows: 

```
java.lang.NoSuchFieldError: isEC
	at sun.security.ssl.Handshaker.getActiveProtocols(Handshaker.java:790)
	at sun.security.ssl.Handshaker.activate(Handshaker.java:549)
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1482)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1351)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1283)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1258)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at com.stripe.net.LiveStripeResponseGetter.createPostConnection(LiveStripeResponseGetter.java:232)
	at com.stripe.net.LiveStripeResponseGetter.makeURLConnectionRequest(LiveStripeResponseGetter.java:392)
	at com.stripe.net.LiveStripeResponseGetter.getStripeResponse(LiveStripeResponseGetter.java:557)
	at com.stripe.net.LiveStripeResponseGetter._rawRequest(LiveStripeResponseGetter.java:475)
	at com.stripe.net.LiveStripeResponseGetter._request(LiveStripeResponseGetter.java:501)
	at com.stripe.net.LiveStripeResponseGetter.request(LiveStripeResponseGetter.java:72)
	at com.stripe.net.APIResource.request(APIResource.java:169)
	at com.stripe.model.Charge.create(Charge.java:622)
	at com.stripe.model.Charge.create(Charge.java:559)
	at Connectors.StripeConnector.chargeCustomer(StripeConnector.java:47)
```

I have implemented stripe elsewhere so i know im passing in all the proper tokens etc. Im running this on Payara 5.181 with a Jersey application on java 1.8.0_102 build and running the stripe-java 5.34.1 version but it appears to be also there on 5.35.0

I can provide more if needed.

**Comment by ob-stripe** [comment]
Hi @colangelo-david. I don't think this is an issue with the library itself, the stack trace shows the error is happening pretty deep in the JDK. I'm not familiar at all with Payara or Jersey but I guess there's something in your Java environment that's preventing the library from establishing a TLS 1.2 connection to Stripe's API servers.

Can you try running your app with `-Djavax.net.debug=ssl` and see if the debug output sheds any more light on the issue?

Also, if it's possible, can you update to the latest Java 8 version (JDK 8u162)?

**Comment by colangelo-david** [comment]
@ob-stripe I have some time set aside to look at this over the next day or so. I was debugging more last night and upgraded to JDK 8U162 and next up is a downgrade to the latest 7 build. I found some tangentially related stuff and it may possibly be colliding with the latest version of GRIZZLY packaged with Payara so Im going to try to downgrade to the last V4 build. Ill let you know what I find.

**Comment by ob-stripe** [comment]
@colangelo-david Were you able to solve the issue?

**Comment by colangelo-david** [comment]
@ob-stripe it looks like things have stabled out. I did a few thing all at once so I'm not sure exactly what fixed it but: 

- Upgraded to Java 162
- Cleared maven cache (which i was doing previously) 
- Rebooted machine 
- Ran with the -Djavax.net.debug=ssl option 

That combination seems to get everything working and I was able to deploy the docker image to ElasticBeanstalk last night without the SSL option and confirm that its working. I think it was some kind of dependency/maven issue. If I have some time ill try and recreate the problem and get to the bottom of it but it looks like its stable for now.

**Comment by ob-stripe** [comment]
@colangelo-david Cool, glad you were able to fix the problem even if you're not 100% sure about the resolution.

AFAIK, the `-Djavax.net.debug=ssl` option only enables some debug output, it doesn't actually change how SSL/TLS connections are handled, so you should safely be able to remove it if things are working now.

I'm closing the issue, but feel free to reply if you have any more questions or want to provide additional information!

**Comment by colangelo-david** [comment]
Sounds good! 

I did not have the option running in the deployed environment, which seemed to be working so i think its all stabilized now. If i have some time I may try and downgrade everything to see if I can recreate the problem but if anyone else find this issue or a similar while using Glassfish/Payara the solution seems to be 

- Upgrade to Java 8_162
- Complete clear maven cache 
- Use Stripe 5.34.0
