### ISSUE TITLE
ClassCastException when trying to create new card

### ISSUE THREAD

**Issue by moga111** [stripe/stripe-java#499]
**Expected:**
`Customer.createCard` to return a card object.

**Actual:**
Response is a type of object "source"

```java
java.lang.ClassCastException: Cannot cast com.stripe.model.Source to com.stripe.model.Card

	at java.lang.Class.cast(Class.java:3369)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.stripe.net.LiveStripeResponseGetter.staticRequest(LiveStripeResponseGetter.java:536)
	at com.stripe.net.LiveStripeResponseGetter.request(LiveStripeResponseGetter.java:74)
	at com.stripe.net.APIResource.request(APIResource.java:202)
	at com.stripe.model.Customer.createCard(Customer.java:398)
	at com.stripe.model.Customer.createCard(Customer.java:366)
```

Here is the code I am using:
```java
        Customer customer = Customer.retrieve(customerId);
        Map<String, Object> customerParams = new HashMap<>();
        customerParams.put("source", token);
        return customer.createCard(customerParams);
```

The card is added successfully, but the problem is only in the response.

**Comment by remi-stripe** [comment]
@moga111 Which type is returned by the method you've defined? My guess is that the issue has to do with that part where you are getting a `Card` from our library but return a different type in your own method.

**Comment by moga111** [comment]
Hey @remi-stripe , thanks for the reply.
I am actually returning `com.stripe.model.Card` I traced the code, and it looks like the response from the server says that the object is of type `source`

```
{
  "id": "src_1CGfAgEF1oKtuDvNK7Lyi",
  "object": "source",
  "amount": null,
  "client_secret": "src_client_secret_Cg1Dp0oTF73zoYfvwj2Fm",
  "created": 1523676926,
  "currency": null,
  "customer": "cus_Cfh9w1SimhPcLu",
  "flow": "none",
  "livemode": false,
  "metadata": {},
  "owner": {
    "address": null,
    "email": null,
    "name": null,
    "phone": null,
    "verified_address": null,
    "verified_email": null,
    "verified_name": null,
    "verified_phone": null
  },
  "statement_descriptor": null,
  "status": "chargeable",
  "type": "card",
  "usage": "reusable",
  "card": {
    "exp_month": 11,
    "exp_year": 2019,
    "brand": "Visa",
    "card_automatically_updated": false,
    "country": "US",
    "cvc_check": "pass",
    "fingerprint": "JYpfQYbqIimCEWtG",
    "funding": "credit",
    "last4": "4242",
    "three_d_secure": "optional",
    "address_line1_check": null,
    "address_zip_check": null,
    "tokenization_method": null,
    "dynamic_last4": null
  }
}

```

**Comment by remi-stripe** [comment]
@moga111 This means that you are creating a Source object and not a Card object. You can not use `createCard()` in that case since this expects the old model of type `Card`.

Instead, you should attach the Source to the Customer using `customer.getSources().create()` instead like this:

```
Customer customer = Customer.retrieve("cus_AFGbOSiITuJVDs");
Map<String, Object> params = new HashMap<String, Object>();
params.put("source", "src_18eYalAHEMiOZZp1l9ZTjSU0");
cardSource = customer.getSources().create(params);
```

This returns an `ExternalAccount` instance which is a parent class for all of those.

**Comment by moga111** [comment]
Amazing! thanks for the help it works now.
The problem is solved.
