### ISSUE TITLE
NPE when deserializing event "batch.request"

### ISSUE THREAD

**Issue by Or4ng3** [stripe/stripe-java#573]
Recently (since 10 august) I started to receive strange webhook events from stripe. All of them have type = "batch.request" and causes NPE when deserializing because they don't have data.object.object field. Not sure if this is stripe service or this library bug.
Tested in versions 6.3 and 5.53.

stacktrace:
```java.lang.NullPointerException
	at com.stripe.model.EventDataDeserializer.deserialize(EventDataDeserializer.java:146)
	at com.stripe.model.EventDataDeserializer.deserialize(EventDataDeserializer.java:17)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
```

webhook event:
```{
  "id": "evt_1CybzG4Yy0rPXJQC5cOuEIpo",
  "object": "event",
  "account": "acct_1************JQC",
  "api_version": "2015-01-11",
  "created": 1534151118,
  "data": {
    "object": {
      "id": "ch_1CwqHQ4Yy0rPXJQCCsg0tnRr",
      "batch_main_request_count": 1,
      "bulk_action": "blk_1Cybyv4Yy0rPXJQCaChrkD2I",
      "livemode": true,
      "response_data": {
        "id": "ch_1CwqHQ4Yy0rPXJQCCsg0tnRr",
        "object": "charge",
        "amount": 2900,
        "amount_refunded": 2900,
        "application": "ca_32zUTHbEYUvUSpduGXtHLwuUvtKsw88M",
        "application_fee": null,
        "balance_transaction": "txn_1CwqHR4Yy0rPXJQCc4cmP2BM",
        "captured": true,
        "card": {
          "id": "card_1CwqHP4Yy0rPXJQCDl3ni4gy",
          "object": "card",
          "address_city": "*********",
          "address_country": "**************",
          "address_line1": "************",
          "address_line1_check": "pass",
          "address_line2": null,
          "address_state": "***",
          "address_zip": "********",
          "address_zip_check": "pass",
          "brand": "MasterCard",
          "country": "**",
          "customer": null,
          "cvc_check": "pass",
          "dynamic_last4": null,
          "exp_month": 11,
          "exp_year": 2019,
          "fingerprint": "****************",
          "funding": "credit",
          "last4": "****",
          "metadata": {},
          "name": "*************",
          "tokenization_method": null,
          "type": "MasterCard"
        },
        "created": 1533729404,
        "currency": "**",
        "customer": null,
        "description": "Charge for order from email *******************",
        "destination": null,
        "dispute": null,
        "failure_code": null,
        "failure_message": null,
        "fraud_details": {},
        "invoice": null,
        "livemode": true,
        "metadata": {
          "ecwidChargeId": "********************",
          "customer_email": "*******************",
          "customer_phone": "***********",
          "customer_name": "*********"
        },
        "on_behalf_of": null,
        "order": null,
        "outcome": {
          "network_status": "approved_by_network",
          "reason": null,
          "seller_message": "Payment complete.",
          "type": "authorized"
        },
        "paid": true,
        "receipt_email": null,
        "receipt_number": null,
        "refunded": true,
        "refunds": [
          {
            "id": "re_1Cybz94Yy0rPXJQC7Fx9LLjk",
            "object": "refund",
            "amount": 2900,
            "balance_transaction": "txn_1Cybz94Yy0rPXJQCiU4vOnTh",
            "charge": "ch_1CwqHQ4Yy0rPXJQCCsg0tnRr",
            "created": 1534151111,
            "currency": "***",
            "metadata": {},
            "reason": null,
            "receipt_number": null,
            "status": "succeeded"
          }
        ],
        "review": null,
        "shipping": {
          "address": {
            "city": "*******",
            "country": "**",
            "line1": "************",
            "line2": "************",
            "postal_code": "******",
            "state": "*********"
          },
          "carrier": null,
          "name": "*********",
          "phone": "***********",
          "tracking_number": null
        },
        "source": {
          "id": "card_1CwqHP4Yy0rPXJQCDl3ni4gy",
          "object": "card",
          "address_city": "*********",
          "address_country": "**************",
          "address_line1": "************",
          "address_line1_check": "pass",
          "address_line2": null,
          "address_state": "***",
          "address_zip": "********",
          "address_zip_check": "pass",
          "brand": "MasterCard",
          "country": "**",
          "customer": null,
          "cvc_check": "pass",
          "dynamic_last4": null,
          "exp_month": 11,
          "exp_year": 2019,
          "fingerprint": "****************",
          "funding": "credit",
          "last4": "****",
          "metadata": {},
          "name": "*************",
          "tokenization_method": null,
          "type": "MasterCard"
        },
        "source_transfer": null,
        "statement_description": null,
        "statement_descriptor": null,
        "status": "paid",
        "transfer_group": null
      },
      "response_http_status": 200
    }
  },
  "livemode": true,
  "pending_webhooks": 1,
  "request": null,
  "type": "batch.request",
  "user_id": "acct_1041RL4Yy0rPXJQC"
}
```

**Comment by remi-stripe** [comment]
@Or4ng3 Those events are for a feature in private beta so the client libraries do not support those at the moment. We should not NPE though for new resource types though. We'll look into adding some logic in the future but for now you should check the type of event before deserializing and ignore those if you don't need them

**Comment by Or4ng3** [comment]
@remi-stripe, Is it possible to disable beta features for our application?

**Comment by remi-stripe** [comment]
@Or4ng3 If you receive this event, it likely means that someone on your team asked to be explicitly part of that beta though and is actively using it. I would recommend reaching out to our support team so that they can help you investigate: https://support.stripe.com/email

**Comment by ob-stripe** [comment]
Closing this due to age. I think this should be fixed in newer library versions, but feel free to reply if you're observing this issue and we'll reopen and investigate.
