### ISSUE TITLE
Method "LiveStripeResponseGetter.handleApiError()" throws unhandled exception "com.google.gson.JsonSyntaxException"

### ISSUE THREAD

**Issue by KoichiSenada** [stripe/stripe-java#588]
Java 8.0
stripe-java library 5.31.0 but the method implementation is currently the very same.

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
    at com.google.gson.Gson.fromJson(Gson.java:887)
    at com.google.gson.Gson.fromJson(Gson.java:852)
    at com.google.gson.Gson.fromJson(Gson.java:801)
    at com.google.gson.Gson.fromJson(Gson.java:773)
    at com.stripe.net.LiveStripeResponseGetter.handleAPIError(LiveStripeResponseGetter.java:663)
    at com.stripe.net.LiveStripeResponseGetter._request(LiveStripeResponseGetter.java:508)
    at com.stripe.net.LiveStripeResponseGetter.request(LiveStripeResponseGetter.java:72)
    at com.stripe.net.APIResource.request(APIResource.java:169)
    at com.stripe.model.Plan.retrieve(Plan.java:219)
    at com.stripe.model.Plan.retrieve(Plan.java:181)
```

My suggestion is that this method should catch any thrown "com.google.gson.JsonSyntaxException" and handle it properly as expected.

**Comment by ob-stripe** [comment]
Hi @KoichiSenada, thanks for the report.

The API should always return valid JSON though, even when returning an error. Can you confirm that this occurred during a request to Stripe's API servers? (I.e. you weren't using stripe-mock or another mock server?)

**Comment by farazahmedsyed** [comment]
Hi, any update on above? I had same issue in customer retrieve function.

**Comment by remi-stripe** [comment]
@farazahmedsyed Would you be able to provide more details about the error?

**Comment by farazahmedsyed** [comment]
@remi-stripe  I am using stripe-java version 3.2.0 library. We usually do not get this error, it looks like that it happens only on a specific time(i.e on 2018-09-12 00:00:XX) multiple times.
Logs:

Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at com.google.gson.Gson.fromJson(Gson.java:717)
	at com.google.gson.Gson.fromJson(Gson.java:689)
	at com.stripe.net.LiveStripeResponseGetter.handleAPIError(LiveStripeResponseGetter.java:588)
	at com.stripe.net.LiveStripeResponseGetter._request(LiveStripeResponseGetter.java:444)
	at com.stripe.net.LiveStripeResponseGetter.request(LiveStripeResponseGetter.java:66)
	at com.stripe.net.APIResource.request(APIResource.java:144)
	at com.stripe.model.Customer.retrieve(Customer.java:371)
	at com.stripe.model.Customer.retrieve(Customer.java:257)

**Comment by remi-stripe** [comment]
Gotcha, if it happens again, can you log more details about the exact request, which resource you were creating or fetching, what the API returned, etc.?

**Comment by farazahmedsyed** [comment]
We were unable to reproduce it. The same request payload was executed successfully after some hours. I don,t think that I can log response from API as the above error occurs when library try to read the response payload.

**Comment by ob-stripe** [comment]
@farazahmedsyed Are you connecting directly to Stripe's API? Or is there any sort of proxy between your server and Stripe?

**Comment by farazahmedsyed** [comment]
there is no proxy though we are using stripe library which is then hitting APIs.
